### ISSUE TITLE
Organizing research

### ISSUE THREAD

**Issue by T145** [T145/magistics#14]
I personally am not very good at organizing the research aspect of the mod, so if anyone has any lore input or wants to just help w/ sorting out the research altogether then it would be greatly appreciated! It saves me the time of going through it all and allows me to focus on the programming. With school being as extremely tight as is, I'm lucky to have even a little bit of time to work on Magistics.

**Comment by MWKGames** [comment]
I think I can help a little bit... What do you want me to do?

**Comment by T145** [comment]
Well, if you head over to the post-init method in the main mod file [here](https://github.com/T145/magistics/blob/rebirth/src/main/java/T145/magistics/common/Magistics.java#L110), you can add in research! To add the localizations, just head over to the [lang file](https://github.com/T145/magistics/blob/rebirth/src/main/resources/assets/magistics/lang/en_US.lang) and add them under the research category. That's basically just how you add it all in! If you add in the lore and recipes it would be an enormous help!

**Comment by MWKGames** [comment]
Actually, this may take a while because I only know basic basics of programming, I'll search for the Thaumcraft API for research and then I'll contact you.

**Comment by T145** [comment]
Well, that's the thing; my system makes it super simple for anyone to add in research! Yes, you will have to know how to add the basic parameters for a [ResearchItem](https://github.com/Azanor/thaumcraft-api/blob/master/research/ResearchItem.java), etc., but that's really simple. I've added the Hungry Ender Chest's research and such, so you can use that as an example.

**Comment by MyDeloreanWontStart** [comment]
I can do lore if you want. I'm retarded at coding, but I can pastbin like a boss

**Comment by T145** [comment]
That would be great, thanks! You just need to edit the en_US.lang file under the lang folder in the resources to add research localizations! Lore for the crystal blocks I've added, as well as the hungry ender chest and iron chests would be great, then I could ship out a release that can hold people over for a while whilst I work on the hardcore stuff

**Comment by MyDeloreanWontStart** [comment]
>edit the en_US.lang file under the lang folder in the resources to add research localizations!

Will try... If I screw something up, than sorry :P

**Comment by MyDeloreanWontStart** [comment]
Nevermind, could I just give you a pastebin? I can barely even find the file and I dont want to screw it up

**Comment by T145** [comment]
You can find the file [here](https://github.com/T145/magistics/blob/master/src/main/resources/assets/magistics/lang/en_US.lang), though I'm fine w/ looking at your stuff through PasteBin. You can use the research that's there as a template if you'd like!

**Comment by MyDeloreanWontStart** [comment]
Yeah, I have the intelligence of a sea lard when it ocmes to these things. Let me just write you a pastebin with some lore. I'll link it in a bit.

**Comment by T145** [comment]
Any progress?

**Comment by MyDeloreanWontStart** [comment]
I did 2 so far, and got bogged with work. Going to get like 5 donw before i show it to ya
