### ISSUE TITLE
Crash on start up with magistics 0.7.6 from curseforge

### ISSUE THREAD

**Issue by crunkazcanbe** [T145/magistics#22]
As the title says http://pastebin.com/MSzjy9kW . I would love to user this mod but as soon as I toss it in my pack it crashes before minecraft can start .

**Comment by T145** [comment]
This is because the Botania API cannot be found somehow. I'll have to either package it in w/ the mod or remove the functionality to fix it; that or you can install Botania.

**Comment by Alaberti** [comment]
I also had this problem but I'm glad it was resolved. Is there any documentation on the Botania requirement? I didn't see any myself when I downloaded the mod; I usually run with Botania anyhow but when error checking other mods I removed it which led me here.

**Comment by T145** [comment]
Botania is not a requirement. The problem was that is was being loaded as one, but that's resolved now since I packaged Botania's API with the mod. Now you can play Magistics bare w/ Thaumcraft!
