### ISSUE TITLE
Some recipe/lore suggestions

### ISSUE THREAD

**Issue by ghost** [T145/magistics#43]
http://pastebin.com/iHGeE9gm

Maybe once some more stuff is implemented/ given a use I could think of some more stuff, if you want.

**Comment by T145** [comment]
1) I think for the Chthonian Furnace I'll make the description "Deserves Ice Cream" :)
2) For the Arcane Singularity, I was planning on having the concept of its old recipe maintained, somehow including nitor and alumentum.

**Comment by MyDeloreanWontStart** [comment]
1) What else does the Chtloennsonsbtuhitgnitnbi *cough cough* furnace do?

2) dunno, maybe add 3 aluminum and 3 nitor instead of the shards?

**Comment by T145** [comment]
1. Acts just like the Infernal Furnace, but will actually suck items into it from the front when powered by redstone!
2. Remember we have the Infusers back :smile:
