### ISSUE TITLE
1.10.2 Block and Item Texturing

### ISSUE THREAD

**Issue by T145** [T145/magistics#52]
Hey guys! I was curious if anyone would be willing to make JSON blockstates and models for some blocks or items in the mod to help me out, or perhaps provide a guide that really helped you out.

**Comment by Royal-Jelly** [comment]
its been some time and you know if you ever need help im here man here is what i used https://mcforge.readthedocs.io/en/latest/blockstates/forgeBlockstates/

**Comment by Royal-Jelly** [comment]
the part on sub models it quite interesting ~

**Comment by T145** [comment]
I've checked out that article, and it was helpful indeed. It doesn't solve the problem I'm having w/ the rendering the infuser though; the top face refuses to render properly in the inventory. Btw, could you pull out the original TC2 crucible sprites? I have the textures for all of the other variants. Once I get those, I can start working on the crucible. My plan as of now is to make Magistics independent of TC, and complete the crucible, infuser, conduit, and vis handling for the first beta release. Also, if you'd like to mess around w/ the JSON models, be my guest!

**Comment by Royal-Jelly** [comment]
I don't know about you but i have a great idea one sec while i get it all typed up and posted seperatly
