### ISSUE TITLE
IS IT FOR REAL THIS TIME??!! ┻━┻ ︵ヽ(`Д´)ﾉ︵﻿ ┻━┻

### ISSUE THREAD

**Issue by 63502** [T145/magistics#56]
I'm still here, surprisingly enough. I don't have the time to do any serious writing right now with my finals happening in the next few weeks, but I am open to bounce random ideas off of.

**Comment by T145** [comment]
I will try my best. Schoolwork + Finals + Job + Girlfriend = 99% of my time, so right now I'm just doing small ports. Over summer break is when I'll be free, and hope to finish the mod by its end.
